# docker build --rm -f Dockerfile.agent -t drone/agent .

FROM golang:1.9.3-stretch
ENV GODEBUG=netdns=go
ADD release/drone-agent /bin/

EXPOSE 3000
HEALTHCHECK CMD ["/bin/drone-agent", "ping"]

ENTRYPOINT ["/bin/drone-agent"]
